name: Develop

on:
  push:
    branches:
      develop

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: cache-build-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          cache-build-${{ env.cache-name }}-
          cache-build-
          cache-
    - name: Install Dependencies
      run: npm ci
      env:
        CI: true
    - name: Linting
      run: npm run lint
      env:
        CI: true
    - name: Npm Configuration
      run: npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - name: Publish Cron Core
      run: npm run dev-publish:cron-code
      env:
        CI: true 
    - name: Publish Ng Cron
      run: npm run dev-publish:ng-cron
      env:
        CI: true 
    - name: Publish Re Cron
      run: npm run dev-publish:re-cron
      env:
        CI: true 
